export const CUSTOM_PAREMETER_RULE_TYPE = "CUSTOM_PAREMETER_RULE_TYPE";
export const CUSTOM_PAREMETER_CODE_EDITOR = "CUSTOM_PAREMETER_CODE_EDITOR";
export const CUSTOM_PAREMETER_RULE_NAME = "CUSTOM_PAREMETER_RULE_NAME";
export const SELECT_SAVED_RULE = "SELECT_SAVED_RULE";
export const COMPARE_FOR_SAVE_CHANGES = "COMPARE_FOR_SAVE_CHANGES";