export const PREPARE_ENTITES_FOR_DELETE = "PREPARE_ENTITES_FOR_DELETE";
export const PREPARE_ENTITES_FOR_DELETE_PULL = "PREPARE_ENTITES_FOR_DELETE_PULL";
export const PREPARE_ENTITES_FOR_DELETE_ALL = "PREPARE_ENTITES_FOR_DELETE_ALL";