export const SET_STABLE_ENTITIES = 'SET_STABLE_ENTITIES';
export const SET_STABLE_TASKS = 'SET_STABLE_TASKS';


export const SET_STABLE_DATA_SEARCH_NAME = 'SET_STABLE_DATA_SEARCH_NAME';
export const SET_STABLE_DATA_NAME = 'SET_STABLE_DATA_NAME';
export const SET_STABLE_DATA_LOGICALNAME = 'SET_STABLE_DATA_LOGICALNAME';
export const SET_STABLE_DATA_MAIN_NAME = 'SET_STABLE_DATA_MAIN_NAME';
export const SET_STABLE_DATA_ETC = 'SET_STABLE_DATA_ETC';