export const SET_TOGGLE_MODAL = "SET_TOGGLE_MODAL";
export const SET_DELETED_ENTITY_NAME_FOR_MODAL = "SET_DELETED_ENTITY_NAME_FOR_MODAL";
export const SET_MODAL_DELETED = "SET_MODAL_DELETED";
export const SET_TOGGLE_MODAL_ACTIONS = "SET_TOGGLE_MODAL_ACTIONS";
export const SET_MODAL_ACTIONS_ALLOW = "SET_MODAL_ACTIONS_ALLOW";
export const SET_MODAL_ADD_ENTITY = "SET_MODAL_ADD_ENTITY";
export const SET_MODAL_ADD_FIELD = "SET_MODAL_ADD_FIELD";